version: '3.3'

services:
    centos:
        build: centos7
        ports:
            - 22:22
            - 80:80
            - 3306:3306
            - 9000:9000
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./www:/home/bitrix/www
            - ./mysql:/var/lib/mysql
        dns:
            - 8.8.8.8
            - 8.8.4.4
        privileged: true
        
    #phpmyadmin:
        #image: phpmyadmin:5.0.2
        #links:
            #- centos:centos
        #environment:
            #PMA_HOST: centos
            #MYSQL_DATABASE: bitrix
            #MYSQL_USER: bitrix
            #MYSQL_PASSWORD: bitrix
            #MYSQL_ROOT_PASSWORD: root
        #restart: always
        #ports:
            #- 8080:80
        #networks:
            #- bitrix-network
#networks:
    #bitrix-network:
        #driver: bridge